# Generated by Django 6.1.1 on 2026-09-25 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='')),
                ('direccion', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('depto', 'Departamento')], default='casa', max_length=20)),
                ('valor_arriendo', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='inmuebles_app.comuna')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles_propios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
